# Generated by Django 5.0.14 on 2025-06-08 20:52

from django.db import migrations
from django.utils.text import slugify

def create_subjects(apps, schema_editor):
    Subject = apps.get_model('courses', 'Subject')
    titles = [
    "Mathematics",
    "Music",
    "Physics",
    "Programming",
    ]
    for title in titles:
        Subject.objects.create(title=title, slug=slugify(title))


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
