# Generated by Django 5.0.14 on 2025-06-08 21:03

from django.db import migrations


def add_welcome_modules(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Module = apps.get_model('courses', 'Module')

    for course in Course.objects.filter(title__icontains="101"):
        Module.objects.get_or_create(
            course=course,
            title="Welcome",
            defaults={
                "description": f"Introduction to {course.subject.title}",
                "order": 0,
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20250608_2052'),
    ]

    operations = [
        migrations.RunPython(add_welcome_modules),
    ]
